---
title: "data_607_repo_assignment"
author: "Maxfield Raynolds; Updates by Gillian McGovern"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
```

## Some basic code for the repo assignment

The following code loads a data set about the features of zoo animals.

```{r load the dataset}
zoo_df <- read_csv("https://raw.githubusercontent.com/mraynolds/data_607/refs/heads/main/zoo_data-1.csv")

head(zoo_df)
```

The following code uses across to convert all the binary indicators of animal features to logical.

```{r The following code converts all of the binary columns to logical}
zoo <- zoo_df |> 
  mutate(across(!animal_name & !legs,as.logical))

head(zoo)
```

## Updates

This code shows how `relocate` makes it easy to move blocks of columns at once:

```{r}
zoo <- zoo %>%
  relocate(where(is.numeric), .after = last_col())

head(zoo)
```

Now all the numeric columns appear after the logical columns.